/* eslint-disable @typescript-eslint/no-misused-promises */

import { useEffect } from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import useJikan from '../hooks/useJikan';

const Home: NextPage = () => {
  const { data, isLoading, isLoadingMore, error, size, setSize } = useJikan();

  // Debugging
  useEffect(() => {
    console.log({ data, isLoading, isLoadingMore, error, size });
  }, [data, isLoading, isLoadingMore, error, size]);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-amber-200 via-violet-600 to-sky-900 bg-fixed">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Anicore
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-3 md:gap-8">
            <button
              type="button"
              className="col-span-3 flex max-w-full flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={() => setSize(size + 1)}
            >
              <h3 className="text-2xl font-bold">{isLoadingMore ? 'Loading...' : 'Load more'}</h3>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
