/* eslint-disable @typescript-eslint/no-misused-promises */

import type { Dispatch, SetStateAction } from 'react';
import { useEffect, useRef, useState } from 'react';
import { type NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useDebounce } from 'use-debounce';

import type { GetServerSideProps, InferGetServerSidePropsType, GetServerSidePropsResult } from 'next';
import axios from 'axios';
import type { Anime } from '../../types/jikan';
import { useRouter } from 'next/router';
import useAnimeDetail from '../../hooks/useAnimeDetail';

const AnimeDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const { data, error, isLoading } = useAnimeDetail(id as string);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[radial-gradient(ellipse_at_bottom,_var(--tw-gradient-stops))] from-amber-200 via-violet-600 to-sky-900 bg-fixed">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">Anicore</h1>
          <h2 className="text-xl font-extrabold tracking-tight text-white sm:text-[2rem]">{data?.title ?? 'lol'}</h2>
        </div>
      </main>
    </>
  );
};

export default AnimeDetail;
