/* eslint-disable @next/next/no-img-element */
/* eslint-disable @typescript-eslint/no-misused-promises */

import { type NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import { useRouter } from 'next/router';
import Spinner from '../../components/Spinner';
import useAnimeDetail from '../../hooks/useAnimeDetail';

const AnimeDetail: NextPage = () => {
  const router = useRouter();
  const { id } = router.query;

  const { data: anime, error, isLoading } = useAnimeDetail(id as string);

  return (
    <>
      <Head>
        <title>{anime?.title ?? 'Loading...'}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-conic-t flex min-h-screen flex-col items-center justify-center from-orange-900 via-amber-100 to-orange-900 bg-fixed">
        <div className="container flex flex-col items-center justify-center space-y-16 px-8 py-32 lg:py-48 lg:px-12">
          <div className="flex flex-col items-center space-y-4">
            <Link href="/">
              <h1 className="bg-conic-tl from-stone-600 via-zinc-900 to-purple-300 bg-clip-text text-5xl font-extrabold tracking-tight text-transparent lg:text-[5rem]">
                Anicore
              </h1>
            </Link>
            <h2 className="text-lg tracking-tight text-gray-800 lg:text-[1.5rem]">The Anime Directory</h2>
            <div className="flex h-full w-full py-16">
              {typeof anime == 'undefined' ? (
                <div className="flex h-64 w-64 max-w-full flex-col items-center justify-center rounded-xl bg-black/60 p-4 text-white hover:bg-black/80 disabled:pointer-events-none disabled:opacity-50">
                  <Spinner />
                </div>
              ) : (
                <>
                  <div className="flex h-full w-full flex-col space-y-16 rounded-xl bg-black/20 p-16 text-white backdrop-blur-lg backdrop-brightness-50">
                    <div className="flex h-full w-full flex-col items-start justify-center space-x-0 space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
                      <img
                        className="max-w-16 h-fit rounded"
                        src={anime.images.jpg.large_image_url}
                        alt={anime.title}
                      />
                      <div className="flex h-full flex-col space-y-4">
                        <h3 className="text-5xl font-bold">{anime.title}</h3>
                        {anime.title_japanese && <h4 className="text-xl">Japanese: {anime.title_japanese}</h4>}
                        <div className="flex flex-col space-x-0 space-y-2 lg:flex-row lg:space-x-2 lg:space-y-0">
                          <span className="text-lg">
                            ⭐️ {anime.score ?? '-'} ({anime.scored_by?.toLocaleString() ?? '-'})
                          </span>
                          <span className="w-fit rounded-lg bg-red-800 px-1.5 py-1 font-semibold uppercase">
                            {anime.type}
                          </span>
                          <span className="w-fit rounded-lg bg-red-800 px-1.5 py-1 font-semibold uppercase">
                            Episodes: {anime.episodes}
                          </span>
                          {anime.demographics?.length > 0 && (
                            <span className="w-fit rounded-lg bg-red-800 px-1.5 py-1 font-semibold uppercase">
                              {anime.demographics.map((d) => d.name).join(', ')}
                            </span>
                          )}
                        </div>
                        <div>{anime.synopsis}</div>
                      </div>
                    </div>
                    <div className="flex h-full w-full flex-col space-y-8">
                      <h4 className="text-lg font-semibold text-white lg:text-[2rem]">Trailer</h4>
                      <iframe
                        className="aspect-video w-full"
                        src={`https://www.youtube-nocookie.com/embed/${anime.trailer.youtube_id}`}
                        title={anime.title}
                        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                        allowFullScreen
                      />
                    </div>
                  </div>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default AnimeDetail;
